[package]
name = "gdb-server"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { path = "../probe-rs", version = "0.3.0" }
gdb-protocol = { version = "0.1.0" }
recap = "0.1.1"
serde = "1.0.1"
pretty_env_logger = "0.3.0"
structopt = "*"
async-std = { version = "1.4.0", features = ["unstable"] }
futures = "*"
log = "0.4.0"
memchr = "2.2.1"